### ISSUE TITLE
support for i8 weights in dense affine layers?

### ISSUE THREAD

**Issue by jdart1** [jw1912/bullet#167]
Looks to me like this is not supported, but I could be wrong. For example trainer/default/builder.rs seems to assume 16-bit weights. Stockfish in fact uses this and with common quantization schemes weights will be limited to an i8 range.

**Comment by jw1912** [comment]
@jdart1 it has been my position for a while that if you're going to the effort of i8 inference, you can also go to the (very little) effort of quantising the network yourself from the unquantised weights (or indeed from the i16 quantised weights as they will be in the correct range).

This is because broadly speaking by the time you get to a point that i8 quantisation is actually worth it, you're going to be doing things like training with a factoriser, having multiple layers and permuting them for speed, etc. All of which require fiddling with the network file in a way that bullet doesn't (and does not intend to) support.

I guess I'll add `i8` as a quantisation target in trainer/default/quant.rs, but won't be changing the default assumption of i16 quantisation in `TrainerBuilder`.

**Comment by jdart1** [comment]
Ok. It did occur to me that post-processing the output is an option.
